AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'lib/generators/*/templates/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'plugins/**/*'
    - 'plugins-*/**/*'
    - 'lib/procedo/formula/language.rb'
    - 'lib/working_set/query_language.rb'
    - 'db/first_runs/**/*'
    - 'db/schema.rb'

Rails:
  Enabled: true
  
Rails/HttpPositionalArguments:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 60