---
activity_families:
  administering: activity_families/administering.jpg
  animal_farming: activity_families/animal_farming.jpg
  plant_farming: activity_families/plant_farming.jpg
  processing: activity_families/processing.jpg
  service_delivering: activity_families/service_delivering.jpg
  tool_maintaining: activity_families/tool_maintaining.jpg
  wine_making: activity_families/wine_making.jpg
chemical_classifications:
  dsd_corrosive: chemical_classifications/dsd_corrosive.png
  dsd_environmental_hazard: chemical_classifications/dsd_environmental_hazard.png
  dsd_explosive: chemical_classifications/dsd_explosive.png
  dsd_extremely_flammable: chemical_classifications/dsd_extremely_flammable.png
  dsd_harmful: chemical_classifications/dsd_harmful.png
  dsd_highly_flammable: chemical_classifications/dsd_highly_flammable.png
  dsd_irritant: chemical_classifications/dsd_irritant.png
  dsd_oxidizing: chemical_classifications/dsd_oxidizing.png
  dsd_toxic: chemical_classifications/dsd_toxic.png
  dsd_very_toxic: chemical_classifications/dsd_very_toxic.png
  ghs_compressed_gas: chemical_classifications/ghs_compressed_gas.png
  ghs_corrosive: chemical_classifications/ghs_corrosive.png
  ghs_environmental_hazard: chemical_classifications/ghs_environmental_hazard.png
  ghs_explosive: chemical_classifications/ghs_explosive.png
  ghs_flammable: chemical_classifications/ghs_flammable.png
  ghs_harmful: chemical_classifications/ghs_harmful.png
  ghs_health_hazard: chemical_classifications/ghs_health_hazard.png
  ghs_oxidizing: chemical_classifications/ghs_oxidizing.png
  ghs_toxic: chemical_classifications/ghs_toxic.png
countries:
  ad: countries/ad.png
  ae: countries/ae.png
  af: countries/af.png
  ag: countries/ag.png
  ai: countries/ai.png
  al: countries/al.png
  am: countries/am.png
  an: countries/an.png
  ao: countries/ao.png
  ar: countries/ar.png
  as: countries/as.png
  at: countries/at.png
  au: countries/au.png
  aw: countries/aw.png
  ax: countries/ax.png
  az: countries/az.png
  ba: countries/ba.png
  bb: countries/bb.png
  bd: countries/bd.png
  be: countries/be.png
  bf: countries/bf.png
  bg: countries/bg.png
  bh: countries/bh.png
  bi: countries/bi.png
  bj: countries/bj.png
  bm: countries/bm.png
  bn: countries/bn.png
  bo: countries/bo.png
  br: countries/br.png
  bs: countries/bs.png
  bt: countries/bt.png
  bv: countries/bv.png
  bw: countries/bw.png
  by: countries/by.png
  bz: countries/bz.png
  ca: countries/ca.png
  cc: countries/cc.png
  cd: countries/cd.png
  cf: countries/cf.png
  cg: countries/cg.png
  ch: countries/ch.png
  ci: countries/ci.png
  ck: countries/ck.png
  cl: countries/cl.png
  cm: countries/cm.png
  cn: countries/cn.png
  co: countries/co.png
  cr: countries/cr.png
  cu: countries/cu.png
  cv: countries/cv.png
  cx: countries/cx.png
  cy: countries/cy.png
  cz: countries/cz.png
  de: countries/de.png
  dj: countries/dj.png
  dk: countries/dk.png
  dm: countries/dm.png
  do: countries/do.png
  dz: countries/dz.png
  ec: countries/ec.png
  ee: countries/ee.png
  eg: countries/eg.png
  eh: countries/eh.png
  er: countries/er.png
  es: countries/es.png
  et: countries/et.png
  fi: countries/fi.png
  fj: countries/fj.png
  fk: countries/fk.png
  fm: countries/fm.png
  fo: countries/fo.png
  fr: countries/fr.png
  ga: countries/ga.png
  gb: countries/gb.png
  gd: countries/gd.png
  ge: countries/ge.png
  gf: countries/gf.png
  gh: countries/gh.png
  gi: countries/gi.png
  gl: countries/gl.png
  gm: countries/gm.png
  gn: countries/gn.png
  gp: countries/gp.png
  gq: countries/gq.png
  gr: countries/gr.png
  gs: countries/gs.png
  gt: countries/gt.png
  gu: countries/gu.png
  gw: countries/gw.png
  gy: countries/gy.png
  hk: countries/hk.png
  hm: countries/hm.png
  hn: countries/hn.png
  hr: countries/hr.png
  ht: countries/ht.png
  hu: countries/hu.png
  id: countries/id.png
  ie: countries/ie.png
  il: countries/il.png
  in: countries/in.png
  io: countries/io.png
  iq: countries/iq.png
  ir: countries/ir.png
  is: countries/is.png
  it: countries/it.png
  jm: countries/jm.png
  jo: countries/jo.png
  jp: countries/jp.png
  ke: countries/ke.png
  kg: countries/kg.png
  kh: countries/kh.png
  ki: countries/ki.png
  km: countries/km.png
  kn: countries/kn.png
  kp: countries/kp.png
  kr: countries/kr.png
  kw: countries/kw.png
  ky: countries/ky.png
  kz: countries/kz.png
  la: countries/la.png
  lb: countries/lb.png
  lc: countries/lc.png
  li: countries/li.png
  lk: countries/lk.png
  lr: countries/lr.png
  ls: countries/ls.png
  lt: countries/lt.png
  lu: countries/lu.png
  lv: countries/lv.png
  ly: countries/ly.png
  ma: countries/ma.png
  mc: countries/mc.png
  md: countries/md.png
  me: countries/me.png
  mg: countries/mg.png
  mh: countries/mh.png
  mk: countries/mk.png
  ml: countries/ml.png
  mm: countries/mm.png
  mn: countries/mn.png
  mo: countries/mo.png
  mp: countries/mp.png
  mq: countries/mq.png
  mr: countries/mr.png
  ms: countries/ms.png
  mt: countries/mt.png
  mu: countries/mu.png
  mv: countries/mv.png
  mw: countries/mw.png
  mx: countries/mx.png
  my: countries/my.png
  mz: countries/mz.png
  na: countries/na.png
  nc: countries/nc.png
  ne: countries/ne.png
  nf: countries/nf.png
  ng: countries/ng.png
  ni: countries/ni.png
  nl: countries/nl.png
  'no': countries/no.png
  np: countries/np.png
  nr: countries/nr.png
  nu: countries/nu.png
  nz: countries/nz.png
  om: countries/om.png
  pa: countries/pa.png
  pe: countries/pe.png
  pf: countries/pf.png
  pg: countries/pg.png
  ph: countries/ph.png
  pk: countries/pk.png
  pl: countries/pl.png
  pm: countries/pm.png
  pn: countries/pn.png
  pr: countries/pr.png
  ps: countries/ps.png
  pt: countries/pt.png
  pw: countries/pw.png
  py: countries/py.png
  qa: countries/qa.png
  re: countries/re.png
  ro: countries/ro.png
  rs: countries/rs.png
  ru: countries/ru.png
  rw: countries/rw.png
  sa: countries/sa.png
  sb: countries/sb.png
  sc: countries/sc.png
  sd: countries/sd.png
  se: countries/se.png
  sg: countries/sg.png
  sh: countries/sh.png
  si: countries/si.png
  sj: countries/sj.png
  sk: countries/sk.png
  sl: countries/sl.png
  sm: countries/sm.png
  sn: countries/sn.png
  so: countries/so.png
  sr: countries/sr.png
  st: countries/st.png
  sv: countries/sv.png
  sy: countries/sy.png
  sz: countries/sz.png
  tc: countries/tc.png
  td: countries/td.png
  tf: countries/tf.png
  tg: countries/tg.png
  th: countries/th.png
  tj: countries/tj.png
  tk: countries/tk.png
  tl: countries/tl.png
  tm: countries/tm.png
  tn: countries/tn.png
  to: countries/to.png
  tr: countries/tr.png
  tt: countries/tt.png
  tv: countries/tv.png
  tw: countries/tw.png
  tz: countries/tz.png
  ua: countries/ua.png
  ug: countries/ug.png
  um: countries/um.png
  us: countries/us.png
  uy: countries/uy.png
  uz: countries/uz.png
  va: countries/va.png
  vc: countries/vc.png
  ve: countries/ve.png
  vg: countries/vg.png
  vi: countries/vi.png
  vn: countries/vn.png
  vu: countries/vu.png
  wf: countries/wf.png
  ws: countries/ws.png
  ye: countries/ye.png
  yt: countries/yt.png
  za: countries/za.png
  zm: countries/zm.png
  zw: countries/zw.png
varieties:
  acer: varieties/acer.jpg
  actinopterygii: varieties/actinopterygii.jpg
  adoxaceae: varieties/adoxaceae.jpg
  ajuga: varieties/ajuga.jpg
  allium: varieties/allium.jpg
  alnus: varieties/alnus.jpg
  althaea: varieties/althaea.jpg
  ananas: varieties/ananas.jpg
  anethum: varieties/anethum.jpg
  angelica: varieties/angelica.jpg
  annonaceae: varieties/annonaceae.jpg
  anthriscus: varieties/anthriscus.jpg
  apium: varieties/apium.jpg
  arachis: varieties/arachis.jpg
  arctium: varieties/arctium.jpg
  artemisia: varieties/artemisia.jpg
  asparagaceae: varieties/asparagaceae.jpg
  avena: varieties/avena.jpg
  aves: varieties/aves.jpg
  bambusa: varieties/bambusa.jpg
  bellis: varieties/bellis.jpg
  berberidaceae: varieties/berberidaceae.jpg
  beta: varieties/beta.jpg
  betula: varieties/betula.jpg
  bison: varieties/bison.jpg
  bivalvia: varieties/bivalvia.jpg
  borago: varieties/borago.jpg
  bos: varieties/bos.jpg
  brassica_napus: varieties/brassica_napus.jpg
  brassica_napus_rapifera: varieties/brassica_napus_rapifera.jpg
  brassica_nigra: varieties/brassica_nigra.jpg
  brassica_oleracea: varieties/brassica_oleracea.jpg
  brassica_oleracea_botrytis: varieties/brassica_oleracea_botrytis.jpg
  brassica_oleracea_gemmifera: varieties/brassica_oleracea_gemmifera.jpg
  brassica_oleracea_gongylodes: varieties/brassica_oleracea_gongylodes.jpg
  brassica_oleracea_italica: varieties/brassica_oleracea_italica.jpg
  brassica_oleracea_sabellica: varieties/brassica_oleracea_sabellica.jpg
  brassica_rapa_pekinensis: varieties/brassica_rapa_pekinensis.jpg
  brassica_rapa_rapa: varieties/brassica_rapa_rapa.jpg
  bromus: varieties/bromus.jpg
  canidae: varieties/canidae.jpg
  cannabis: varieties/cannabis.jpg
  capra: varieties/capra.jpg
  capsicum: varieties/capsicum.jpg
  carpinus: varieties/carpinus.jpg
  carum: varieties/carum.jpg
  castanea: varieties/castanea.jpg
  centaurea: varieties/centaurea.jpg
  ceratonia: varieties/ceratonia.jpg
  cercis: varieties/cercis.jpg
  cervidae: varieties/cervidae.jpg
  chamaemelum: varieties/chamaemelum.jpg
  chenopodium: varieties/chenopodium.jpg
  chrysopogon: varieties/chrysopogon.jpg
  cicer: varieties/cicer.jpg
  cichorium: varieties/cichorium.jpg
  citrullus: varieties/citrullus.jpg
  citrus_maxima: varieties/citrus_maxima.jpg
  citrus_medica: varieties/citrus_medica.jpg
  citrus_reticulata: varieties/citrus_reticulata.jpg
  citrus_sinensis: varieties/citrus_sinensis.jpg
  coffea: varieties/coffea.jpg
  coriandrum: varieties/coriandrum.jpg
  corylus: varieties/corylus.jpg
  crambe: varieties/crambe.jpg
  crataegus: varieties/crataegus.jpg
  crocus: varieties/crocus.jpg
  crocus_sativus: varieties/crocus_sativus.jpg
  cucumis: varieties/cucumis.jpg
  cucumis_melo: varieties/cucumis_melo.jpg
  cucurbita: varieties/cucurbita.jpg
  cuminum: varieties/cuminum.jpg
  curcuma: varieties/curcuma.png
  cydonia: varieties/cydonia.jpg
  cynara: varieties/cynara.jpg
  dactylis: varieties/dactylis.jpg
  daucus: varieties/daucus.jpg
  diervillaceae: varieties/diervillaceae.jpg
  elaeagnus: varieties/elaeagnus.jpg
  equidae: varieties/equidae.jpg
  eruca: varieties/eruca.jpg
  eucalyptus: varieties/eucalyptus.jpg
  fagopyrum: varieties/fagopyrum.jpg
  fagus: varieties/fagus.jpg
  felidae: varieties/felidae.jpg
  festuca: varieties/festuca.jpg
  ficus: varieties/ficus.jpg
  foeniculum: varieties/foeniculum.jpg
  forsythia: varieties/forsythia.jpg
  fortunella: varieties/fortunella.jpg
  fragaria: varieties/fragaria.jpg
  fraxinus: varieties/fraxinus.jpg
  galium: varieties/galium.jpg
  gastropoda: varieties/gastropoda.jpg
  gleditsia: varieties/gleditsia.jpg
  glycine: varieties/glycine.jpg
  gossypium: varieties/gossypium.jpg
  guizotia: varieties/guizotia.jpg
  helianthus: varieties/helianthus.jpg
  helianthus_tuberosus: varieties/helianthus_tuberosus.jpg
  hevea: varieties/hevea.jpg
  hibiscus: varieties/hibiscus.jpg
  hippophae: varieties/hippophae.jpg
  hordeum: varieties/hordeum.jpg
  humulus: varieties/humulus.jpg
  hydrangeaceae: varieties/hydrangeaceae.jpg
  hypericum: varieties/hypericum.jpg
  insecta: varieties/insecta.jpg
  ipomoea_batatas: varieties/ipomoea_batatas.jpg
  juglans: varieties/juglans.jpg
  koelreuteria: varieties/koelreuteria.jpg
  laburnum: varieties/laburnum.jpg
  lactuca: varieties/lactuca.jpg
  lathyrus: varieties/lathyrus.jpg
  lavandula: varieties/lavandula.jpg
  lens: varieties/lens.jpg
  lepidium: varieties/lepidium.jpg
  leporidae: varieties/leporidae.jpg
  leucanthemum: varieties/leucanthemum.jpg
  ligustrum: varieties/ligustrum.jpg
  limonium: varieties/limonium.jpg
  linum: varieties/linum.jpg
  lolium: varieties/lolium.jpg
  lotus: varieties/lotus.jpg
  lupinus: varieties/lupinus.jpg
  malus: varieties/malus.jpg
  malva: varieties/malva.jpg
  mangifera: varieties/mangifera.jpg
  manihot: varieties/manihot.jpg
  medicago: varieties/medicago.jpg
  melilotus: varieties/melilotus.jpg
  melissa: varieties/melissa.jpg
  mentha: varieties/mentha.jpg
  miscanthus: varieties/miscanthus.jpg
  morus: varieties/morus.jpg
  musa: varieties/musa.jpg
  myocastoridae: varieties/myocastoridae.jpg
  nicotiana: varieties/nicotiana.jpg
  ocimum: varieties/ocimum.jpg
  olea: varieties/olea.jpg
  onobrychis: varieties/onobrychis.jpg
  origanum: varieties/origanum.jpg
  ornithopus: varieties/ornithopus.jpg
  oryza: varieties/oryza.jpg
  ovis: varieties/ovis.jpg
  panicum: varieties/panicum.jpg
  papaver: varieties/papaver.jpg
  pastinaca: varieties/pastinaca.jpg
  persea: varieties/persea.jpg
  petroselinum: varieties/petroselinum.jpg
  phacelia: varieties/phacelia.jpg
  phalaris: varieties/phalaris.jpg
  phaseolus: varieties/phaseolus.jpg
  phleum: varieties/phleum.jpg
  pimpinella: varieties/pimpinella.jpg
  pistacia: varieties/pistacia.jpg
  pisum: varieties/pisum.jpg
  plantago: varieties/plantago.jpg
  poa: varieties/poa.jpg
  poaceae: varieties/poaceae.jpg
  poncirus: varieties/poncirus.jpg
  primulaceae: varieties/primulaceae.jpg
  prunus: varieties/prunus.jpg
  pyrus: varieties/pyrus.jpg
  quercus: varieties/quercus.jpg
  raphanus: varieties/raphanus.jpg
  ribes: varieties/ribes.jpg
  ricinus: varieties/ricinus.jpg
  robinia: varieties/robinia.jpg
  rosa: varieties/rosa.jpg
  rosmarinus: varieties/rosmarinus.jpg
  rubus: varieties/rubus.jpg
  rumex: varieties/rumex.jpg
  rutaceae: varieties/rutaceae.jpg
  saccharum: varieties/saccharum.jpg
  salix: varieties/salix.jpg
  salvia: varieties/salvia.jpg
  satureja: varieties/satureja.jpg
  secale: varieties/secale.jpg
  setaria: varieties/setaria.jpg
  shepherdia: varieties/shepherdia.jpg
  silybum: varieties/silybum.jpg
  solanum: varieties/solanum.jpg
  solanum_lycopersicum: varieties/solanum_lycopersicum.jpg
  solanum_melongena: varieties/solanum_melongena.jpg
  solanum_torvum: varieties/solanum_torvum.jpg
  solanum_tuberosum: varieties/solanum_tuberosum.jpg
  sorghum: varieties/sorghum.jpg
  spinacia: varieties/spinacia.jpg
  spiraea: varieties/spiraea.jpg
  suidae: varieties/suidae.jpg
  theobroma: varieties/theobroma.jpg
  thymus: varieties/thymus.jpg
  tilia: varieties/tilia.jpg
  tragopogon: varieties/tragopogon.jpg
  trifolium: varieties/trifolium.jpg
  trigonella: varieties/trigonella.jpg
  triticosecale: varieties/triticosecale.jpg
  triticum: varieties/triticum.jpg
  valeriana: varieties/valeriana.jpg
  valerianella: varieties/valerianella.jpg
  vanilla: varieties/vanilla.jpg
  veronica: varieties/veronica.jpg
  vicia: varieties/vicia.jpg
  vigna: varieties/vigna.jpg
  viola: varieties/viola.jpg
  vitex: varieties/vitex.jpg
  vitis: varieties/vitis.png
  zea: varieties/zea.jpg
